### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'words'

### ISSUE THREAD

**Issue by ministar683** [tjflexic/kaggle-word2vec-movie-reviews#1]
I got this error when I run python generate_d2v.py，I don't know why? the full log:
Training Doc2Vec model...
2016-01-13 13:05:08,774 : INFO : collecting all words and their counts
2016-01-13 13:05:08,774 : INFO : PROGRESS: at example #0, processed 0 words (0/s), 0 word types, 0 tags
Traceback (most recent call last):
  File "generate_d2v.py", line 73, in <module>
    model_dm.build_vocab(all_reviews)
  File "/Users/youxu-ios2/ml/kaggle-word2vec-movie-reviews/kaggle/lib/python2.7/site-packages/gensim/models/word2vec.py", line 495, in build_vocab
    self.scan_vocab(sentences, trim_rule=trim_rule)  # initial survey
  File "/Users/youxu-ios2/ml/kaggle-word2vec-movie-reviews/kaggle/lib/python2.7/site-packages/gensim/models/doc2vec.py", line 639, in scan_vocab
    document_length = len(document.words)
AttributeError: 'numpy.ndarray' object has no attribute 'words'

**Comment by angkai** [comment]
I also got this error

  File "/kaggle-word2vec-movie-reviews-master/generate_d2v.py", line 73, in <module>
    model_dm.build_vocab(all_reviews)
  File "\Anaconda2\lib\site-packages\gensim\models\word2vec.py", line 523, in build_vocab
    self.scan_vocab(sentences, progress_per=progress_per, trim_rule=trim_rule)  # initial survey
  File "\Anaconda2\lib\site-packages\gensim\models\doc2vec.py", line 654, in scan_vocab
    if isinstance(document.words, string_types):
AttributeError: 'numpy.ndarray' object has no attribute 'words'
